version: '3.9'

services:
  client:
    container_name: client-container
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    build: ./client
    ports:
      - ${CLIENT_PORT_DOCKER}
    stdin_open: true
  server:
    container_name: server-container
    environment:
      DB_CONNECT: ${DB_CONNECT}
      TOKEN_SECRET: ${TOKEN_SECRET}
      PORT: ${SERVER_PORT}
    build: ./server
    ports:
      - ${SERVER_PORT_DOCKER}
  mongo:
    image: mongo
    ports:
      - ${DATABASE_PORT_DOCKER}
      